version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
